apiVersion: apps/v1
kind: Deployment
metadata:
  name: ""
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/managed-by: redis-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      containers:
        - name: default
          image: redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          args:
            - "--save"
            - ""
            - "--appendonly"
            - "no"
