apiVersion: v1
kind: Service
metadata:
  name: ""
  labels:
    app.kubernetes.io/managed-by: redis-operator
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - name: redis-port
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: NodePort
